config/routes.rb
Cenit::Application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    confirmations: 'confirmations'
  } do
    get 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  root to: 'rails_admin/main#dashboard'
  get ':group/dashboard', to: 'rails_admin/main#dashboard', as: :dashboard_group
  get 'dashboard', to: 'rails_admin/main#dashboard'
  get 'terms', to: 'rails_admin/main#dashboard'

  get 'explore/:api', to: 'api#explore', as: :explore_api
  post 'write/:api', to: 'api#write', as: :write_api

  service_path =
    if Cenit.service_path.present?
      "/#{Cenit.service_path}".squeeze('/')
    else
      '/service'
    end
  Cenit.service_path service_path
  if Cenit.service_url.present?
    Cenit.routed_service_url(Cenit.service_url)
  else
    mount Cenit::Service::Engine => service_path
    Cenit.routed_service_url(Cenit.homepage + service_path)
  end


  oauth_path =
    if Cenit.oauth_path.present?
      "/#{Cenit.oauth_path}".squeeze('/')
    else
      '/oauth'
    end
  Cenit.oauth_path oauth_path

  match "#{oauth_path}/authorize", to: 'oauth#index', via: [:get, :post]
  get "#{oauth_path}/callback", to: 'oauth#callback'
  post "#{oauth_path}/token", to: 'oauth#token'

  get 'captcha', to: 'captcha#index'
  get 'captcha/:token', to: 'captcha#index'
  get '/file/:model/:field/:id', to: 'file#index'
  get '/file/:model/:field/:id/*file(.:format)', to: 'file#index'

  namespace :api do
    namespace :v1 do
      post '/auth/ping', to: 'api#auth'
      get '/public/:model', to: 'api#index', ns: 'setup'
      get '/public/:model/:id(.:format)', to: 'api#show', ns: 'setup', defaults: { format: 'json' }, constraints: { format: /(json)/ }
      post '/setup/user', to: 'api#new_user'
      post '/:ns/push', to: 'api#push'
      post '/:ns/:model', to: 'api#new'
      get '/:ns/:model', to: 'api#index', defaults: { format: 'json' }
      get '/:ns/:model/:id', to: 'api#show', defaults: { format: 'json' }
      get '/:ns/:model/:id/:view', to: 'api#content', defaults: { format: 'json' }
      delete '/:ns/:model/:id', to: 'api#destroy'
      post '/:ns/:model/:id/pull', to: 'api#pull'
      post '/:ns/:model/:id/run', to: 'api#run'
      match '/auth', to: 'api#auth', via: [:head]
      match '/*path', to: 'api#cors_check', via: [:options]
    end

    namespace :v2 do
      post '/auth/ping', to: 'api#auth'
      get '/public/:model', to: 'api#index', ns: 'setup'
      get '/public/:model/:id(.:format)', to: 'api#show', ns: 'setup', defaults: { format: 'json' }, constraints: { format: /(json)/ }
      post '/setup/user', to: 'api#new_user'
      post '/:ns/push', to: 'api#push'
      post '/:ns/:model', to: 'api#new'
      post '/:ns/:model/digest', to: 'api#data_type_digest'
      get '/:ns/:model', to: 'api#index', defaults: { format: 'json' }
      get '/:ns/:model/:id', to: 'api#show', defaults: { format: 'json' }
      post '/:ns/:model/:id', to: 'api#update'
      delete '/:ns/:model/:id', to: 'api#destroy'
      post '/:ns/:model/:id/pull', to: 'api#pull'
      post '/:ns/:model/:id/run', to: 'api#run'
      get '/:ns/:model/:id/retry', to: 'api#retry'
      get '/:ns/:model/:id/authorize', to: 'api#authorize'
      get '/:ns/:model/:id/:view', to: 'api#content', defaults: { format: 'json' }
      match '/auth', to: 'api#auth', via: [:head]
      match '/*path', to: 'api#cors_check', via: [:options]
    end

    namespace :v3 do
      post '/setup/user', to: 'api#new_user'
      post '/:__ns_/:__model_', to: 'api#new'
      get '/:__ns_/:__model_', to: 'api#index', defaults: { format: 'json' }
      get '/:__ns_/:__model_/:__id_', to: 'api#show', defaults: { format: 'json' }
      post '/:__ns_/:__model_/:__id_', to: 'api#update'
      match '/:__ns_/:__model_/:__id_/digest', to: 'api#digest', via: [:get, :post]
      match '/:__ns_/:__model_/:__id_/digest/*path', to: 'api#digest', via: [:get, :post]
      delete '/:__ns_/:__model_/:__id_', to: 'api#destroy'
      match '/*path', to: 'api#cors_check', via: [:options]
    end
  end

  match '/app/*path', to: 'app#cors_check', via: [:options]
  match 'app/:id_or_ns' => 'app#index', via: ::Setup::Webhook::SYM_METHODS
  match 'app/:id_or_ns/:app_slug' => 'app#index', via: ::Setup::Webhook::SYM_METHODS
  match 'app/:id_or_ns/:app_slug/*path' => 'app#index', via: ::Setup::Webhook::SYM_METHODS

  get 'remote_shared_collection/:id', to: 'rails_admin/main#remote_shared_collection'
  get 'remote_shared_collection/:id/pull', to: 'rails_admin/main#remote_shared_collection'

  namespace :contact_us do
    controller :contacts do
      post '/contacts' => :create
      get :thanks
    end
  end

  mount RailsAdmin::Engine => '/', as: 'rails_admin'

  match '/:model_name/:id/swagger/*path' => 'rails_admin/main#swagger', via: [:all]

  get '/:model_name/*id', to: 'rails_admin/main#show'

  Cenit.options.keys.grep(/:route:draw:listener\Z/).each do |source_key|
    if (listener = Cenit[source_key]).is_a?(String)
      listener =
        begin
          Cenit[source_key].constantize
        rescue
          nil
        end
    end
    listener && listener.try(:on_route_draw, self)
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController

  before_filter { warden.authenticate! scope: :user if check_params }

  def index
    skip_consent = false
    if request.get?
      if @errors.blank?
        if @app_id && (@app_id.tenant == Account.current || @app_id.registered?)
          @token = Cenit::Token.create(data: { scope: @scope.to_s, redirect_uri: @redirect_uri, state: params[:state] }).token
          access_grant = Cenit::OauthAccessGrant.where(application_id: @app_id).first
          skip_consent =
            if access_grant
              @grant_scope = access_grant.oauth_scope
              @scope = @scope.diff(@grant_scope)
              @already_authorized = @grant_scope > @scope
            else
              false
            end
          skip_consent &&= !params[:show_consent].to_b
          @consent_action = :allow if skip_consent
        else
          @errors << 'Unregistered app'
        end
      end
    end
    if request.post? || skip_consent
      if (token = Cenit::Token.where(token: @token).first) &&
        token.data.is_a?(Hash) &&
        (redirect_uri = URI.parse(token.data['redirect_uri'])) &&
        (scope = token.data['scope'])
        token.destroy
        params = {}
        if (state = token.data['state'])
          params[:state] = state
        end
        if @consent_action == :allow
          code_token = Cenit::OauthCodeToken.create(scope: scope, user_id: User.current.id)
          params[:code] = code_token.token
        else
          params[:error] = 'Access denied'
        end
        redirect_uri.query = redirect_uri.query.to_s + params.to_param
        redirect_to redirect_uri.to_s
      else
        @errors << 'Consent time out'
      end
    end
    render :bad_request, status: :bad_request if @errors.present?
  end

  def token
    response = {}
    response_code = :bad_request
    errors = ''
    token_class =
      case (grant_type = params[:grant_type])
      when 'authorization_code'
        errors += 'Code missing. ' unless (auth_value = params[:code])
        Cenit::OauthCodeToken
      when 'refresh_token'
        errors += 'Refresh token missing. ' unless (auth_value = params[:refresh_token])
        Cenit::OauthRefreshToken
      else
        errors += 'Invalid grant_type parameter.'
        nil
      end
    if errors.blank? && (token = token_class.where(token: auth_value).first)
      token.set_current_tenant!
      token.destroy unless token.long_term?
      if (app_id = Cenit::ApplicationId.where(identifier: params[:client_id]).first) &&
        app_id.app.secret_token == params[:client_secret]
        if grant_type == 'authorization_code'
          errors += 'Invalid redirect_uri. ' unless app_id.nil? || app_id.redirect_uris.include?(params[:redirect_uri])
        end
      else
        errors += 'Invalid client credentials. '
      end
      begin
        response = Cenit::OauthAccessToken.for(app_id, token.scope, token.user_id, token.tenant)
        response_code = :ok
      rescue Exception => ex
        errors += ex.message
      end if errors.blank?
    else
      errors += "Invalid #{grant_type.gsub('_', ' ')}." if token_class
    end
    response = { error: errors } if errors.present?
    headers['Access-Control-Allow-Origin'] = request.headers['Origin'] || ::Cenit.homepage
    render json: response, status: response_code
  end

  def callback
    redirect_uri = rails_admin.index_path(Setup::Authorization.to_s.underscore.tr('/', '~'))
    error = params[:error]
    if (cenit_token = CallbackAuthorizationToken.where(token: params[:state] || session[:oauth_state]).first) &&
      cenit_token.set_current_tenant! && (authorization = cenit_token.authorization)
      begin
        authorization.metadata[:redirect_token] = redirect_token = Devise.friendly_token
        redirect_uri =
          if (app = cenit_token.app_id) && (app = app.app)
            callback_authorization_id = authorization.metadata[:callback_authorization_id] ||
              authorization.metadata['callback_authorization_id'] ||
              authorization.id
            callback_params = authorization.metadata[:callback_authorization_params] ||
              authorization.metadata['callback_authorization_params']
            unless callback_params.is_a?(Hash)
              callback_params = {}
            end
            callback_params[:redirect_token] = redirect_token
            if app.authentication_method == :user_credentials
              callback_params[:'X-User-Access-Key'] = Tenant.current.owner.number
              callback_params[:'X-User-Access-Token'] = Tenant.current.owner.token
            end
            "/app/#{app.slug_id}/authorization/#{callback_authorization_id}?" + callback_params.to_param
          elsif (token_data = cenit_token.data).is_a?(Hash) && token_data.key?('redirect_uri')
            token_data['redirect_uri']
          else
            rails_admin.show_path(model_name: authorization.class.to_s.underscore.tr('/', '~'), id: authorization.id.to_s) + "?redirect_token=#{redirect_token}"
          end
        resolve_params = params.reject { |k, _| %w(controller action).include?(k) }
        if authorization.accept_callback?(resolve_params)
          resolve_params[:cenit_token] = cenit_token
          authorization.resolve!(resolve_params)
        else
          authorization.cancel!
        end
      rescue Exception => ex
        json_params =
          begin
            params.to_json
          rescue
            params.to_s
          end
        report = Setup::SystemReport.create_from(ex, "Error on OAuth Callback controller with params: #{json_params}")
        error = "An unexpected error occurs (#{ex.message}). Ask for support by supplying this code: #{report.id}"
      end
    else
      error = 'Invalid state data'
    end

    cenit_token.delete if cenit_token

    if error.present?
      error = error[1..500] + '...' if error.length > 500
      flash[:error] = error.html_safe
      uri =
        begin
          URI.parse(redirect_uri)
        rescue
          nil
        end
      if uri && !uri.relative?
        uri.query = [uri.query, "error=#{error}"].compact.join('&')
        redirect_uri = uri.to_s
      end
    end

    redirect_to redirect_uri
  end

  def check_params
    @errors = []
    send("check_#{@_action_name}")
  end

  def check_index
    if request.get?
      @errors << 'Missing client_id.' unless (@client_id = params[:client_id])
      if (@response_type = params[:response_type])
        @errors << 'Invalid response_type.' unless @response_type == 'code'
      else
        @errors << 'Missing response_type.'
      end
      @errors << 'Missing redirect_uri.' unless (@redirect_uri = params[:redirect_uri])
      @errors << 'Missing scope.' unless (@scope = params[:scope])
      if (@app_id = Cenit::ApplicationId.where(identifier: @client_id).first)
        unless @app_id.redirect_uris.include?(@redirect_uri)
          @errors << 'Invalid redirect_uri'
        end
      else
        @errors << 'Invalid credentials'
      end if @errors.blank?
      if @scope.is_a?(String)
        @scope = Cenit::OauthScope.new(@scope)
      end
      @errors << 'Invalid scope' unless @scope.nil? || @scope.valid?
    else
      @errors << 'Consent time out' unless (@token = params[:token])
      @consent_action = params[:allow] ? :allow : :deny
    end
    true
  end

  def check_callback
    false
  end

  def check_token
    false
  end

  protected :check_params, :check_index, :check_callback, :check_token
end

app/views/oauth/_description.html.haml
:ruby
  begin
    cenit_oauth_scope = ::Cenit::OauthScope.new(scope).access_by_ids
    methods = Hash.new { |h, k| h[k] = [] }
    cenit_oauth_scope.each_criteria do |method, criteria|
      methods[method] = Setup::DataType.where(criteria)
    end
    basic = Hash.new
    if !cenit_oauth_scope.openid_set.empty?
      basic[:openid]= cenit_oauth_scope.openid_set.to_a
      basic[:openid].map! do |d|
        case d
        when Cenit::OauthScope::OPENID_EMAIL_TOKEN
          I18n.t('admin.oauth.openid.email')
        when Cenit::OauthScope::OPENID_PROFILE_TOKEN
          I18n.t('admin.oauth.openid.profile')
        else
          d
        end
      end
      basic[:openid].delete_if { |a| a == Cenit::OauthScope::OPENID_TOKEN }
    end
    if !cenit_oauth_scope.super_methods_set.empty?
      basic['super_methods_set']= cenit_oauth_scope.super_methods_set.to_a
      basic['super_methods_set'].map! do |d|
        case d
        when Cenit::OauthScope::CREATE_TOKEN
          I18n.t('admin.oauth.super_methods.create')
        when Cenit::OauthScope::READ_TOKEN
          I18n.t('admin.oauth.super_methods.read')
        when Cenit::OauthScope::UPDATE_TOKEN
          I18n.t('admin.oauth.super_methods.update')
        when Cenit::OauthScope::DELETE_TOKEN
          I18n.t('admin.oauth.super_methods.delete')
        when Cenit::OauthScope::DIGEST_TOKEN
          I18n.t('admin.oauth.super_methods.digest')
        else
          d
        end
      end
    end
    if cenit_oauth_scope.auth?
      basic[Cenit::OauthScope::AUTH_TOKEN]= true
    end
    if cenit_oauth_scope.offline_access?
      basic[Cenit::OauthScope::OFFLINE_ACCESS_TOKEN]= true
    end
    if cenit_oauth_scope.multi_tenant?
      basic[Cenit::OauthScope::MULTI_TENANT_TOKEN]= true
    end
    basic = basic.merge(methods)
    html = '<ul class="scope-description">'
    basic.each do |key, value|
      case key
      when Cenit::OauthScope::OPENID_TOKEN
        value = value.join(',')
        html+= "<li>#{value}</li>"
      when 'super_methods_set'
        value = value.join(',')
        html+= "<li>#{value}</li>"
      else
        if value == true
          case key
          when Cenit::OauthScope::AUTH_TOKEN
            auth_description = t('admin.oauth.auth_desc')
            key = I18n.t('admin.oauth.auth')+'<a href="#" data-toggle="tooltip" title="'+ auth_description+'"><i class="fa fa-info-circle" aria-hidden="true"></i></a>'
          when Cenit::OauthScope::OFFLINE_ACCESS_TOKEN
           offline_access_description = t('admin.oauth.offline_access_desc')
            key = I18n.t('admin.oauth.offline_access')+'<a href="#" data-toggle="tooltip" title="'+ offline_access_description+'"><i class="fa fa-info-circle" aria-hidden="true"></i></a>'
          when Cenit::OauthScope::MULTI_TENANT_TOKEN
           multi_tenant_description = t('admin.oauth.multi_tenant_desc')
            key = I18n.t('admin.oauth.multi_tenant')+'<a href="#" data-toggle="tooltip" title="'+ multi_tenant_description +'"><i class="fa fa-info-circle" aria-hidden="true"></i></a>'
          else
            key
          end
          html+= "<li>#{key}</li>"
        else
          next unless (count = value.count) > 0
          max_data_type_to_show = 3
          config = RailsAdmin.config(::Setup::DataType)
          am = config.abstract_model
          if count > max_data_type_to_show
            i = 0
            first_links = []
            value.each do |dt|
              if (i < max_data_type_to_show)
                label = dt.send(config.object_label_method)
                link = link_to(label, rails_admin.show_path(model_name: ::Setup::DataType.to_s.underscore.gsub('/', '~'), id: dt.id),target: '_blank')
                first_links.push(link)
                i+=1
              else
                break
              end

            end
            first_links = first_links.to_sentence(options = { last_word_connector: ', ' })

            message = "<span>Showing data types for #{key} method</span>"
            filter_token = Cenit::Token.create(data: { criteria: value.selector, message: message }, token_span: 1.hours)
            link_more = link_to("more", rails_admin.index_path(model_name: ::Setup::DataType.to_s.underscore.gsub('/', '~'), filter_token: filter_token.token), target: '_blank' )
            links = "#{first_links} and #{count - max_data_type_to_show} #{link_more}"
          else
            links = value.collect do |dt|
              label = dt.send(config.object_label_method)
              link_to(label, rails_admin.show_path(model_name: ::Setup::DataType.to_s.underscore.gsub('/', '~'), id: dt.id),target: '_blank')
            end.to_sentence
          end
          case key
          when Cenit::OauthScope::READ_TOKEN
            key =  I18n.t('admin.oauth.access.read')
          when Cenit::OauthScope::CREATE_TOKEN
            key = I18n.t('admin.oauth.access.create')
          when Cenit::OauthScope::UPDATE_TOKEN
            key = I18n.t('admin.oauth.access.update')
          when Cenit::OauthScope::DELETE_TOKEN
            key = I18n.t('admin.oauth.access.delete')
          when Cenit::OauthScope::DIGEST_TOKEN
            key = I18n.t('admin.oauth.access.digest')
          else
            key
          end
          html+= "<li>#{key}: <span>#{links}</span></li>"
        end
      end
    end
    html += "</ul>"
    html.html_safe
  rescue Exception => ex
    "ERROR: #{ex.message}"
  end
= html.html_safe

app/views/oauth/bad_request.html.haml
.user-auth.container
  .col-xs-12.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
    .panel.panel-default.oauth-authorize
      .panel-heading.text-center
        %span.cenit-logo
          =image_tag 'logo_cenitsaas_web.png'
        %span.cenit-hub{style: 'color: black;'}= 'any BROKER'
      .panel-body
        .col-xs-12.actions.bad
          .action-title
            %i.fa.fa-times
            %span
              = 'Bad request'
          .action-description
            %ul
              - @errors.each do |error|
                %li
                  = error

app/views/oauth/index.html.haml
.user-auth.container
  .col-xs-12.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
    .panel.panel-default.oauth-authorize
      .panel-heading.text-center
        %span.cenit-logo
          =image_tag 'logo_cenitsaas_web.png'
        %span.cenit-hub{style: 'color: black;'}= 'any BROKER'
      .panel-body
        - if @errors.present?
          %h3
            = 'Bad request'
            - @errors.each do |error|
              %li
                = error
        - else
          - if current_user.picture
            .col-xs-12.images-container
              %span
                = image_tag(@app_id.app.configuration.logo, alt: '', class: 'img-circle')
              %span.user-img
                = image_tag(current_user.picture_url, alt: '', class: 'img-circle')
            %h4.text-center
              = 'Application'
              %label
                = @app_id.name
            - unless @grant_scope.blank?
              .col-xs-12.actions.granted
                .action-title
                  %i.fa.fa-check
                  %span
                    = 'Already have access to:'
                .action-description
                  = render partial: 'oauth/description', locals: {scope: @grant_scope}
            - unless @scope.blank?
              .col-xs-12.actions.request
                .action-title
                  %i.fa.fa-question
                  %span
                    = 'Is requesting access to:'
                .action-description
                  = render partial: 'oauth/description', locals: {scope: @scope}
      .panel-footer.clearfix
        .text-center
          = form_tag(url: oauth_authorize_path) do
            = hidden_field_tag :token, @token
            = button_tag 'Deny', name: :deny, class: 'btn btn-danger'
            = button_tag 'Allow', name: :allow, class: 'btn btn-success'
%script
  $(function () {
  $('[data-toggle="tooltip"]').tooltip()
  })